---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-build
spec:
  workspaces:
    - name: source
      description: The git repo
  steps:
    - name: file-before-tweak
      image: quay.io/openshift/origin-cli:latest
      workingDir: /workspace/source
      command: ["/bin/bash", "-c"]
      args:
        - |-
          cat index.html 
    - name: run-tweak
      image: quay.io/openshift/origin-cli:latest
      workingDir: /workspace/source
      command: ["/bin/bash", "-c"]
      args:
        - |-
          sed -i 's/very/VERY/g' index.html 
    - name: file-after-tweak
      image: quay.io/openshift/origin-cli:latest
      workingDir: /workspace/source
      command: ["/bin/bash", "-c"]
      args:
        - |-
          cat index.html 
